# Generated by Django 5.2.1 on 2025-05-29 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название района')),
                ('polygon', models.TextField(blank=True, null=True, verbose_name='Полигон района (временное текстовое поле)')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата прогноза')),
                ('temperature', models.FloatField(verbose_name='Температура (°C)')),
                ('precipitation', models.FloatField(default=0.0, verbose_name='Осадки (мм)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='core.district', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Прогноз',
                'verbose_name_plural': 'Прогнозы',
            },
        ),
        migrations.CreateModel(
            name='Overload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('overload_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Уровень перегрузки (1-10)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание перегрузки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overloads', to='core.district', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Перегрузка',
                'verbose_name_plural': 'Перегрузки',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата рекомендации')),
                ('recommendation_text', models.TextField(verbose_name='Рекомендация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.district', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
            },
        ),
    ]
